name: DESTROY ALL VPC ENDPOINTS-spoke

on:
  push:
    branches:
      - main

  workflow_dispatch:
permissions:
  id-token: write
  contents: read

jobs:
  destroy-vpc-endpoints:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume:  arn:aws:iam::434097521299:role/testingdummy
          aws-region: ap-south-1

      - name: Find VPC Endpoints
        run: |
          echo "Finding all VPC endpoints in ap-south-1..."

          aws ec2 describe-vpc-endpoints \
            --region ap-south-1 \
            --query 'VpcEndpoints[*].[VpcEndpointId,VpcId,ServiceName,State]' \
            --output table

      - name: Destroy ALL VPC Endpoints in Spoke VPC
        run: |
          VPC_ID="vpc-012c100251b60e49c"

          echo "Target Spoke VPC: $VPC_ID"

          ENDPOINT_IDS=$(aws ec2 describe-vpc-endpoints \
            --region ap-south-1 \
            --filters "Name=vpc-id,Values=$VPC_ID" \
            --query 'VpcEndpoints[*].VpcEndpointId' \
            --output text)

          if [ -z "$ENDPOINT_IDS" ]; then
            echo "No VPC endpoints found."
            exit 0
          fi

          echo "Deleting:"
          echo "$ENDPOINT_IDS"

          aws ec2 delete-vpc-endpoints \
            --region ap-south-1 \
            --vpc-endpoint-ids $ENDPOINT_IDS

      - name: Wait for deletion
        run: |
          sleep 20

      - name: Verify VPC Endpoints
        run: |
          VPC_ID="vpc-012c100251b60e49c"

          echo "Checking remaining endpoints..."

          aws ec2 describe-vpc-endpoints \
            --region ap-south-1 \
            --filters "Name=vpc-id,Values=$VPC_ID" \
            --query 'VpcEndpoints[*].[VpcEndpointId,ServiceName,State]' \
            --output table   