name: DESTROY - ALL Phase 4 VPC ENDPOINTS

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume:  arn:aws:iam::434097521299:role/testingdummy 
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Show Terraform Resources
        run: terraform state list

      - name: Terraform Destroy
        run: terraform destroy -auto-approve

      - name: Check Remaining VPC Endpoints
        run: |
          aws ec2 describe-vpc-endpoints \
            --region ap-south-1 \
            --query 'VpcEndpoints[*].[VpcEndpointId,VpcId,ServiceName,State]' \
            --output table  